import { Word, WordBank } from './types';

export const WORD_BANK_1: WordBank = {
  id: 'bank-1',
  name: 'Age 12',
  words: [
    { id: '1-1', word: 'abundant', definition: 'Existing or available in large quantities; plentiful.', example: 'The garden was full of abundant flowers in the spring.' },
    { id: '1-2', word: 'beacon', definition: 'A fire or light set up in a high or prominent position as a warning, signal, or celebration.', example: 'The lighthouse served as a beacon for ships at sea.' },
    { id: '1-3', word: 'clarity', definition: 'The quality of being coherent and intelligible.', example: 'The teacher explained the math problem with great clarity.' },
    { id: '1-4', word: 'deteriorate', definition: 'Become progressively worse.', example: 'The old house began to deteriorate after years of neglect.' },
    { id: '1-5', word: 'elude', definition: 'Evade or escape from (a danger, enemy, or pursuer), typically in a skillful or cunning way.', example: 'The clever fox managed to elude the hunters.' },
    { id: '1-6', word: 'factor', definition: 'A circumstance, fact, or influence that contributes to a result or outcome.', example: 'Hard work is a key factor in achieving success.' },
    { id: '1-7', word: 'garment', definition: 'An item of clothing.', example: 'She wore a beautiful silk garment to the party.' },
    { id: '1-8', word: 'hostile', definition: 'Unfriendly; antagonistic.', example: 'The two rival teams had a hostile relationship.' },
    { id: '1-9', word: 'improvise', definition: 'Create and perform (music, drama, or verse) spontaneously without preparation.', example: 'When he forgot his lines, he had to improvise.' },
    { id: '1-10', word: 'jovial', definition: 'Cheerful and friendly.', example: 'The party was full of jovial people celebrating.' },
    { id: '1-11', word: 'knack', definition: 'An acquired or natural skill at performing a task.', example: 'She has a knack for solving difficult puzzles.' },
    { id: '1-12', word: 'leeway', definition: 'The amount of freedom to move or act that is available.', example: 'The boss gave him some leeway to finish the project.' },
    { id: '1-13', word: 'marvel', definition: 'Be filled with wonder or astonishment.', example: 'We could only marvel at the beauty of the sunset.' },
    { id: '1-14', word: 'nurture', definition: 'Care for and encourage the growth or development of.', example: 'It is important to nurture young plants so they grow strong.' },
    { id: '1-15', word: 'obstacle', definition: 'A thing that blocks one\'s way or prevents or hinders progress.', example: 'The fallen tree was an obstacle on the road.' },
    { id: '1-16', word: 'plummet', definition: 'Fall or drop straight down at high speed.', example: 'The temperature began to plummet as the sun went down.' },
    { id: '1-17', word: 'quench', definition: 'Satisfy (one\'s thirst) by drinking.', example: 'A cold glass of water will quench your thirst.' },
    { id: '1-18', word: 'reluctant', definition: 'Unwilling and hesitant; disinclined.', example: 'He was reluctant to share his secret with anyone.' },
    { id: '1-19', word: 'salvage', definition: 'Rescue (a wrecked or disabled ship or its cargo) from loss at sea.', example: 'They managed to salvage some old photos from the fire.' },
    { id: '1-20', word: 'terrain', definition: 'A stretch of land, especially with regard to its physical features.', example: 'The rugged terrain made the hike very challenging.' },
    { id: '1-21', word: 'unanimous', definition: '(of two or more people) fully in agreement.', example: 'The class was unanimous in choosing the field trip destination.' },
    { id: '1-22', word: 'vacant', definition: '(of a premise) having no fixtures, furniture, or inhabitants; empty.', example: 'The old building has been vacant for many years.' },
    { id: '1-23', word: 'weary', definition: 'Feeling or showing tiredness, especially as a result of excessive exertion or lack of sleep.', example: 'The long journey made the travelers very weary.' },
    { id: '1-24', word: 'yield', definition: 'Produce or provide (a natural, agricultural, or industrial product).', example: 'The apple trees yield a lot of fruit every year.' },
    { id: '1-25', word: 'zeal', definition: 'Great energy or enthusiasm in pursuit of a cause or an objective.', example: 'She worked with great zeal to finish the project on time.' },
    { id: '1-26', word: 'anticipate', definition: 'Regard as probable; expect or predict.', example: 'We anticipate a large crowd at the school play.' },
    { id: '1-27', word: 'barren', definition: '(of land) too poor to produce much or any vegetation.', example: 'The desert is a barren landscape with very few plants.' },
    { id: '1-28', word: 'conspicuous', definition: 'Standing out so as to be clearly visible.', example: 'The bright red sign was very conspicuous.' },
    { id: '1-29', word: 'dense', definition: 'Closely compacted in substance.', example: 'The forest was so dense that it was hard to see through the trees.' },
    { id: '1-30', word: 'equivalent', definition: 'Equal in value, amount, function, meaning, etc.', example: 'One dollar is equivalent to four quarters.' },
    { id: '1-31', word: 'formulate', definition: 'Create or devise methodically (a strategy or a proposal).', example: 'The team worked together to formulate a winning plan.' },
    { id: '1-32', word: 'genuine', definition: 'Truly what something is said to be; authentic.', example: 'The antique dealer confirmed the painting was a genuine masterpiece.' },
    { id: '1-33', word: 'hazardous', definition: 'Risky; dangerous.', example: 'The icy roads made driving extremely hazardous.' },
    { id: '1-34', word: 'ignite', definition: 'Catch fire or cause to catch fire.', example: 'A single spark can ignite a massive forest fire.' },
    { id: '1-35', word: 'jargon', definition: 'Special words or expressions used by a particular profession or group.', example: 'The computer manual was full of technical jargon.' },
    { id: '1-36', word: 'kinship', definition: 'Blood relationship or a sharing of characteristics or origins.', example: 'The two cousins felt a strong sense of kinship.' },
    { id: '1-37', word: 'linger', definition: 'Stay in a place longer than necessary because of a reluctance to leave.', example: 'The smell of fresh bread continued to linger in the air.' },
    { id: '1-38', word: 'meager', definition: '(of something provided or available) lacking in quantity or quality.', example: 'The hikers had to survive on a meager supply of food.' },
    { id: '1-39', word: 'negotiate', definition: 'Try to reach an agreement or compromise by discussion with others.', example: 'The two countries met to negotiate a peace treaty.' },
    { id: '1-40', word: 'optimist', definition: 'A person who tends to be hopeful and confident about the future.', example: 'Despite the challenges, he remained an eternal optimist.' },
    { id: '1-41', word: 'peculiar', definition: 'Strange or odd; unusual.', example: 'The bird made a very peculiar sound that I had never heard before.' },
    { id: '1-42', word: 'quest', definition: 'A long or arduous search for something.', example: 'The knights went on a quest to find the legendary sword.' },
    { id: '1-43', word: 'retrieve', definition: 'Get or bring (something) back from somewhere.', example: 'The dog ran into the water to retrieve the ball.' },
    { id: '1-44', word: 'skeptical', definition: 'Not easily convinced; having doubts or reservations.', example: 'I was skeptical about his story until I saw the evidence.' },
    { id: '1-45', word: 'toxic', definition: 'Poisonous; very harmful or unpleasant in a pervasive or insidious way.', example: 'Certain mushrooms are toxic and should never be eaten.' },
    { id: '1-46', word: 'unique', definition: 'Being the only one of its kind; unlike anything else.', example: 'Every snowflake has a unique pattern.' },
    { id: '1-47', word: 'vibrant', definition: 'Full of energy and enthusiasm.', example: 'The city market was a vibrant place full of colors and sounds.' },
    { id: '1-48', word: 'wary', definition: 'Feeling or showing caution about possible dangers or problems.', example: 'The cat was wary of the new dog in the house.' },
    { id: '1-49', word: 'xenon', definition: 'A chemical element that is a heavy, colorless, odorless noble gas.', example: 'Xenon is used in some high-intensity lamps.' },
    { id: '1-50', word: 'yearn', definition: 'Have an intense feeling of longing for something.', example: 'After months away, he began to yearn for his home.' },
    { id: '1-51', word: 'ambition', definition: 'A strong desire to do or to achieve something.', example: 'Her ambition is to become a world-famous scientist.' },
    { id: '1-52', word: 'benevolent', definition: 'Well meaning and kindly.', example: 'The benevolent king donated his wealth to the poor.' },
    { id: '1-53', word: 'capacity', definition: 'The maximum amount that something can contain.', example: 'The stadium was filled to its maximum capacity.' },
    { id: '1-54', word: 'drastic', definition: 'Likely to have a strong or far-reaching effect; radical and extreme.', example: 'The company had to take drastic measures to save money.' },
    { id: '1-55', word: 'efficient', definition: 'Achieving maximum productivity with minimum wasted effort or expense.', example: 'The new solar panels are much more efficient than the old ones.' },
    { id: '1-56', word: 'frugal', definition: 'Sparing or economical with regard to money or food.', example: 'By being frugal, they managed to save enough for a vacation.' },
    { id: '1-57', word: 'generate', definition: 'Cause (something, especially emotion or situation) to arise or come about.', example: 'The wind turbines generate clean electricity for the town.' },
    { id: '1-58', word: 'habitat', definition: 'The natural home or environment of an animal, plant, or other organism.', example: 'The rainforest is the natural habitat for many rare birds.' },
    { id: '1-59', word: 'inevitable', definition: 'Certain to happen; unavoidable.', example: 'Change is an inevitable part of life.' },
    { id: '1-60', word: 'jubilant', definition: 'Feeling or expressing great happiness and triumph.', example: 'The crowd was jubilant after their team won the championship.' },
    { id: '1-61', word: 'latitude', definition: 'The angular distance of a place north or south of the earth\'s equator.', example: 'The explorer recorded the latitude and longitude of the island.' },
    { id: '1-62', word: 'monotonous', definition: 'Dull, tedious, and lacking in variety and interest.', example: 'The long drive across the plains was very monotonous.' },
    { id: '1-63', word: 'noteworthy', definition: 'Interesting, significant, or unusual.', example: 'The scientist made several noteworthy discoveries during her research.' },
    { id: '1-64', word: 'objective', definition: '(of a person or their judgment) not influenced by personal feelings or opinions.', example: 'A judge must remain objective when hearing a case.' },
    { id: '1-65', word: 'paraphrase', definition: 'Express the meaning of (the writer or speaker or something written or spoken) using different words.', example: 'Can you paraphrase that paragraph in your own words?' },
    { id: '1-66', word: 'quandary', definition: 'A state of perplexity or uncertainty over what to do in a difficult situation.', example: 'He was in a quandary about whether to accept the new job.' },
    { id: '1-67', word: 'rigorous', definition: 'Extremely thorough, exhaustive, or accurate.', example: 'The athletes underwent a rigorous training program.' },
    { id: '1-68', word: 'substitute', definition: 'A person or thing acting or serving in place of another.', example: 'We had a substitute teacher while our regular teacher was sick.' },
    { id: '1-69', word: 'tangible', definition: 'Perceptible by touch.', example: 'The tension in the room was almost tangible.' },
    { id: '1-70', word: 'ultimate', definition: 'Being or happening at the end of a process; final.', example: 'Winning the gold medal was his ultimate goal.' },
    { id: '1-71', word: 'validate', definition: 'Check or prove the validity or accuracy of (something).', example: 'The data was used to validate the scientist\'s theory.' },
    { id: '1-72', word: 'wholesome', definition: 'Conducive to or suggestive of good health and physical well-being.', example: 'The family enjoyed a wholesome meal of fresh vegetables.' },
    { id: '1-73', word: 'abbreviate', definition: 'Shorten (a word, phrase, or text).', example: 'We often abbreviate "Street" to "St." on envelopes.' },
    { id: '1-74', word: 'boisterous', definition: '(of a person, event, or behavior) noisy, energetic, and cheerful; rowdy.', example: 'The boisterous children played loudly in the park.' },
    { id: '1-75', word: 'collaborate', definition: 'Work jointly on an activity, especially to produce or create something.', example: 'The two artists decided to collaborate on a large mural.' },
    { id: '1-76', word: 'diligent', definition: 'Having or showing care and conscientiousness in one\'s work or duties.', example: 'She is a diligent student who always finishes her homework.' },
    { id: '1-77', word: 'exaggerate', definition: 'Represent (something) as being better or worse than it really is.', example: 'He tends to exaggerate the size of the fish he catches.' },
    { id: '1-78', word: 'futile', definition: 'Incapable of producing any useful result; pointless.', example: 'It is futile to try to stop the tide from coming in.' },
    { id: '1-79', word: 'grievance', definition: 'A real or imagined wrong or other cause for complaint or protest.', example: 'The workers filed a grievance about their low pay.' },
    { id: '1-80', word: 'hypocrisy', definition: 'The practice of claiming to have moral standards or beliefs to which one\'s own behavior does not conform.', example: 'It was sheer hypocrisy for him to complain about laziness.' },
    { id: '1-81', word: 'impartial', definition: 'Treating all rivals or disputants equally; fair and just.', example: 'The referee must be impartial and follow the rules.' },
    { id: '1-82', word: 'jeopardize', definition: 'Put (someone or something) into a situation in which there is a danger of loss, harm, or failure.', example: 'Bad weather could jeopardize the success of the mission.' },
    { id: '1-83', word: 'legislation', definition: 'Laws, considered collectively.', example: 'The government passed new legislation to protect the environment.' },
    { id: '1-84', word: 'meticulous', definition: 'Showing great attention to detail; very careful and precise.', example: 'The architect was meticulous in his drawings for the new building.' },
    { id: '1-85', word: 'nonchalant', definition: '(of a person or manner) feeling or appearing casually calm and relaxed.', example: 'She gave a nonchalant shrug when asked about her success.' },
    { id: '1-86', word: 'obscure', definition: 'Not discovered or known about; uncertain.', example: 'The origins of the ancient language remain obscure.' },
    { id: '1-87', word: 'pessimist', definition: 'A person who tends to see the worst aspect of things or believe that the worst will happen.', example: 'Don\'t be such a pessimist; I\'m sure everything will work out.' },
    { id: '1-88', word: 'reiterate', definition: 'Say something again or a number of times, typically for emphasis or clarity.', example: 'The teacher had to reiterate the instructions several times.' },
    { id: '1-89', word: 'strenuous', definition: 'Requiring or using great exertion.', example: 'Hiking up the mountain was a very strenuous activity.' },
    { id: '1-90', word: 'tentative', definition: 'Not certain or fixed; provisional.', example: 'We have a tentative plan for the weekend, but it might change.' },
    { id: '1-91', word: 'unison', definition: 'Simultaneous performance of action or utterance of speech.', example: 'The choir sang the final notes in perfect unison.' },
    { id: '1-92', word: 'versatile', definition: 'Able to adapt or be adapted to many different functions or activities.', example: 'A smartphone is a very versatile tool for communication.' },
    { id: '1-93', word: 'widespread', definition: 'Found or distributed over a large area or among a number of people.', example: 'The news of the discovery gained widespread attention.' },
    { id: '1-94', word: 'adversary', definition: 'One\'s opponent in a contest, conflict, or dispute.', example: 'He respected his adversary on the tennis court.' },
    { id: '1-95', word: 'bizarre', definition: 'Very strange or unusual, especially so as to cause interest or amusement.', example: 'The movie had a bizarre plot that kept everyone guessing.' },
    { id: '1-96', word: 'chronological', definition: '(of a record of events) starting with the earliest and following the order in which they occurred.', example: 'The history book listed the events in chronological order.' },
    { id: '1-97', word: 'discretion', definition: 'The quality of behaving or speaking in such a way as to avoid causing offense or revealing private information.', example: 'The doctor handled the sensitive information with great discretion.' },
    { id: '1-98', word: 'eloquent', definition: 'Fluent or persuasive in speaking or writing.', example: 'The president gave an eloquent speech that inspired the nation.' },
    { id: '1-99', word: 'formidable', definition: 'Inspiring fear or respect through being impressively large, powerful, intense, or capable.', example: 'The mountain range presented a formidable challenge to the climbers.' },
    { id: '1-100', word: 'resilient', definition: '(of a person or animal) able to withstand or recover quickly from difficult conditions.', example: 'The community was resilient and rebuilt quickly after the storm.' },
  ]
};

export const WORD_BANK_2: WordBank = {
  id: 'bank-2',
  name: 'Age 8',
  words: [
    { id: '2-1', word: 'admire', definition: 'To look at something or someone with respect and approval.', example: 'I really admire how hard you work on your homework.' },
    { id: '2-2', word: 'ancient', definition: 'Something that is very, very old.', example: 'The pyramids in Egypt are ancient buildings.' },
    { id: '2-3', word: 'arrange', definition: 'To put things in a neat or specific order.', example: 'Please arrange your books on the shelf.' },
    { id: '2-4', word: 'astonish', definition: 'To surprise someone very much.', example: 'The magician\'s trick will astonish the audience.' },
    { id: '2-5', word: 'boundary', definition: 'A line that marks the edge of an area.', example: 'The fence marks the boundary of our backyard.' },
    { id: '2-6', word: 'calculate', definition: 'To find an answer using math.', example: 'Can you calculate how many apples we need for the pie?' },
    { id: '2-7', word: 'caution', definition: 'Being careful to avoid danger.', example: 'Use caution when crossing a busy street.' },
    { id: '2-8', word: 'century', definition: 'A period of one hundred years.', example: 'My great-grandmother lived for almost a century.' },
    { id: '2-9', word: 'chamber', definition: 'A room, often a private or special one.', example: 'The king met his advisors in the royal chamber.' },
    { id: '2-10', word: 'column', definition: 'A tall, vertical post used to support a building.', example: 'The front of the library has many white columns.' },
    { id: '2-11', word: 'concentrate', definition: 'To give all your attention to something.', example: 'It is hard to concentrate when it is noisy.' },
    { id: '2-12', word: 'conclude', definition: 'To bring something to an end or finish.', example: 'The speaker will conclude her talk with a short story.' },
    { id: '2-13', word: 'confess', definition: 'To admit that you did something wrong.', example: 'He decided to confess that he broke the vase.' },
    { id: '2-14', word: 'confident', definition: 'Feeling sure of yourself and your abilities.', example: 'She felt confident that she would do well on the test.' },
    { id: '2-15', word: 'connect', definition: 'To join two or more things together.', example: 'You need to connect the dots to see the picture.' },
    { id: '2-16', word: 'consider', definition: 'To think carefully about something.', example: 'Please consider my idea before you say no.' },
    { id: '2-17', word: 'consist', definition: 'To be made up of something.', example: 'The team will consist of five players.' },
    { id: '2-18', word: 'consume', definition: 'To eat, drink, or use something up.', example: 'The fire began to consume the dry wood.' },
    { id: '2-19', word: 'contrast', definition: 'To look at how two things are different.', example: 'The black cat is a sharp contrast to the white snow.' },
    { id: '2-20', word: 'contribute', definition: 'To give something to help a person or group.', example: 'Everyone can contribute a small amount of money to the charity.' },
    { id: '2-21', word: 'creature', definition: 'Any living thing that can move, like an animal.', example: 'A butterfly is a beautiful creature.' },
    { id: '2-22', word: 'damage', definition: 'Harm that is caused to something.', example: 'The storm caused some damage to the roof.' },
    { id: '2-23', word: 'decision', definition: 'A choice that you make after thinking.', example: 'It was a difficult decision, but I chose the red bike.' },
    { id: '2-24', word: 'decline', definition: 'To say no to something politely.', example: 'I had to decline the invitation because I was busy.' },
    { id: '2-25', word: 'decrease', definition: 'To make something smaller or less.', example: 'The store decided to decrease the price of the toys.' },
    { id: '2-26', word: 'delicate', definition: 'Something that is easily broken or hurt.', example: 'The wings of a butterfly are very delicate.' },
    { id: '2-27', word: 'device', definition: 'A tool or machine made for a special purpose.', example: 'A compass is a device used to find your way.' },
    { id: '2-28', word: 'diagram', definition: 'A drawing that explains how something works.', example: 'The diagram shows the parts of a flower.' },
    { id: '2-29', word: 'digest', definition: 'To break down food in your stomach.', example: 'It takes time for your body to digest a big meal.' },
    { id: '2-30', word: 'disease', definition: 'An illness or sickness.', example: 'The doctor helped the child recover from the disease.' },
    { id: '2-31', word: 'display', definition: 'To show something so that it can be seen.', example: 'The museum has a display of old coins.' },
    { id: '2-32', word: 'distant', definition: 'Something that is far away in space or time.', example: 'The stars are very distant from the Earth.' },
    { id: '2-33', word: 'divide', definition: 'To separate something into two or more parts.', example: 'Please divide the pizza into eight slices.' },
    { id: '2-34', word: 'drowsy', definition: 'Feeling sleepy or half-asleep.', example: 'The warm sun made me feel very drowsy.' },
    { id: '2-35', word: 'effort', definition: 'The physical or mental energy needed to do something.', example: 'It takes a lot of effort to climb a steep hill.' },
    { id: '2-36', word: 'elegant', definition: 'Graceful and stylish in appearance or manner.', example: 'She wore an elegant dress to the party.' },
    { id: '2-37', word: 'enable', definition: 'To make it possible for someone to do something.', example: 'The new ramp will enable people in wheelchairs to enter the building.' },
    { id: '2-38', word: 'enormous', definition: 'Very large in size, quantity, or extent.', example: 'The elephant is an enormous animal.' },
    { id: '2-39', word: 'escape', definition: 'To get away from a place where you are being held.', example: 'The bird managed to escape from its cage.' },
    { id: '2-40', word: 'examine', definition: 'To look at something very carefully.', example: 'The doctor will examine your throat to see if it is red.' },
    { id: '2-41', word: 'example', definition: 'Something that shows what other things of the same kind are like.', example: 'Can you give me an example of a mammal?' },
    { id: '2-42', word: 'excellent', definition: 'Extremely good or outstanding.', example: 'You did an excellent job on your science project!' },
    { id: '2-43', word: 'exclaim', definition: 'To cry out suddenly, especially in surprise or pain.', example: '"Look at that!" she decided to exclaim.' },
    { id: '2-44', word: 'exhaust', definition: 'To make someone feel very tired.', example: 'The long hike will exhaust the children.' },
    { id: '2-45', word: 'expensive', definition: 'Costing a lot of money.', example: 'A new car is very expensive.' },
    { id: '2-46', word: 'explain', definition: 'To make something clear by giving details.', example: 'The teacher will explain how to solve the problem.' },
    { id: '2-47', word: 'explore', definition: 'To travel through an unfamiliar area to learn about it.', example: 'We decided to explore the woods behind our house.' },
    { id: '2-48', word: 'extreme', definition: 'Very great in degree or intensity.', example: 'The desert can have extreme heat during the day.' },
    { id: '2-49', word: 'famous', definition: 'Known about by many people.', example: 'The Eiffel Tower is a famous landmark.' },
    { id: '2-50', word: 'fascinate', definition: 'To interest someone very much.', example: 'The stories about space will fascinate the students.' },
    { id: '2-51', word: 'feast', definition: 'A large meal, typically one in celebration of something.', example: 'The family gathered for a Thanksgiving feast.' },
    { id: '2-52', word: 'flexible', definition: 'Able to bend easily without breaking.', example: 'A rubber band is very flexible.' },
    { id: '2-53', word: 'focus', definition: 'To give all your attention to something.', example: 'You need to focus on your work to finish it.' },
    { id: '2-54', word: 'fortune', definition: 'A large amount of money or assets.', example: 'The businessman made a fortune in the stock market.' },
    { id: '2-55', word: 'fragile', definition: 'Easily broken or damaged.', example: 'Be careful with that glass vase; it is very fragile.' },
    { id: '2-56', word: 'frantic', definition: 'Wild or distraught with fear, anxiety, or other emotion.', example: 'The mother was frantic when she couldn\'t find her child.' },
    { id: '2-57', word: 'frequent', definition: 'Happening or done many times at short intervals.', example: 'We make frequent trips to the library.' },
    { id: '2-58', word: 'frontier', definition: 'A line or border separating two countries.', example: 'The explorers traveled to the western frontier.' },
    { id: '2-59', word: 'furious', definition: 'Extremely angry.', example: 'He was furious when he found out someone had lied to him.' },
    { id: '2-60', word: 'generous', definition: 'Showing a readiness to give more of something than is strictly necessary.', example: 'She is very generous and always shares her snacks.' },
    { id: '2-61', word: 'gentle', definition: 'Mild in temperament or behavior; kind or tender.', example: 'The nurse was very gentle when she cleaned the wound.' },
    { id: '2-62', word: 'glimpse', definition: 'A very quick look at something.', example: 'I caught a glimpse of the deer before it ran away.' },
    { id: '2-63', word: 'glorious', definition: 'Having, worthy of, or bringing fame or admiration.', example: 'The sunset was a glorious sight to behold.' },
    { id: '2-64', word: 'graceful', definition: 'Having or showing grace or elegance.', example: 'The ballet dancer was very graceful on stage.' },
    { id: '2-65', word: 'gradual', definition: 'Taking place or progressing slowly or by degrees.', example: 'The hill has a gradual slope that is easy to climb.' },
    { id: '2-66', word: 'grateful', definition: 'Feeling or showing an appreciation of kindness; thankful.', example: 'I am grateful for all the help you gave me.' },
    { id: '2-67', word: 'greedy', definition: 'Having or showing an intense and selfish desire for something.', example: 'The greedy child wanted all the cookies for himself.' },
    { id: '2-68', word: 'guarantee', definition: 'A formal promise or assurance that certain conditions will be fulfilled.', example: 'The store offers a guarantee on all of its products.' },
    { id: '2-69', word: 'guilty', definition: 'Responsible for a specified wrongdoing or error.', example: 'He felt guilty about breaking the window.' },
    { id: '2-70', word: 'harbor', definition: 'A place on the coast where ships may find shelter.', example: 'The boats were safe in the harbor during the storm.' },
    { id: '2-71', word: 'healthy', definition: 'In good physical or mental condition.', example: 'Eating fruits and vegetables helps you stay healthy.' },
    { id: '2-72', word: 'hesitate', definition: 'To pause before saying or doing something.', example: 'Don\'t hesitate to ask if you have any questions.' },
    { id: '2-73', word: 'hollow', definition: 'Having an empty space inside.', example: 'A drum is hollow so that it can make a sound.' },
    { id: '2-74', word: 'humble', definition: 'Having or showing a modest or low estimate of one\'s own importance.', example: 'The famous scientist remained humble despite his success.' },
    { id: '2-75', word: 'humid', definition: 'Marked by a relatively high level of water vapor in the atmosphere.', example: 'The air felt very humid before the rain started.' },
    { id: '2-76', word: 'identical', definition: 'Similar in every detail; exactly alike.', example: 'The twins wore identical outfits to school.' },
    { id: '2-77', word: 'ignore', definition: 'To pay no attention to something or someone.', example: 'It is best to ignore people who are being mean.' },
    { id: '2-78', word: 'imagine', definition: 'To form a mental image or concept of something.', example: 'Can you imagine what it would be like to live on Mars?' },
    { id: '2-79', word: 'imitate', definition: 'To copy the behavior or appearance of someone or something.', example: 'The parrot can imitate many different sounds.' },
    { id: '2-80', word: 'immediate', definition: 'Occurring or done at once; instant.', example: 'The doctor provided immediate help to the injured person.' },
    { id: '2-81', word: 'impatient', definition: 'Having or showing a tendency to be quickly irritated or provoked.', example: 'He grew impatient while waiting for the bus.' },
    { id: '2-82', word: 'important', definition: 'Of great significance or value.', example: 'It is important to wear a helmet when riding a bike.' },
    { id: '2-83', word: 'improve', definition: 'To make or become better.', example: 'You can improve your reading skills by practicing every day.' },
    { id: '2-84', word: 'include', definition: 'To comprise or contain as part of a whole.', example: 'The price of the meal does not include a drink.' },
    { id: '2-85', word: 'independent', definition: 'Free from outside control; not depending on another\'s authority.', example: 'The cat is a very independent animal.' },
    { id: '2-86', word: 'indicate', definition: 'To point out or show something.', example: 'The sign will indicate which way to go.' },
    { id: '2-87', word: 'individual', definition: 'Single; separate.', example: 'Each individual student has their own desk.' },
    { id: '2-88', word: 'inform', definition: 'To give someone facts or information.', example: 'Please inform me if you are going to be late.' },
    { id: '2-89', word: 'inner', definition: 'Situated inside or further in; internal.', example: 'The inner part of the fruit is very sweet.' },
    { id: '2-90', word: 'innocent', definition: 'Not guilty of a crime or offense.', example: 'The jury found the man innocent of all charges.' },
    { id: '2-91', word: 'inquire', definition: 'To ask for information from someone.', example: 'I called the store to inquire about their hours.' },
    { id: '2-92', word: 'instrument', definition: 'A tool or implement, especially one for delicate or scientific work.', example: 'A thermometer is an instrument used to measure temperature.' },
    { id: '2-93', word: 'intelligent', definition: 'Having or showing intelligence, especially of a high level.', example: 'Dolphins are very intelligent animals.' },
    { id: '2-94', word: 'intend', definition: 'To have a course of action as one\'s purpose or objective; plan.', example: 'I intend to finish my book by the end of the week.' },
    { id: '2-95', word: 'interest', definition: 'The feeling of wanting to know or learn about something or someone.', example: 'She has a great interest in learning about history.' },
    { id: '2-96', word: 'interior', definition: 'The inner part of something; inside.', example: 'The interior of the house was painted a bright blue.' },
    { id: '2-97', word: 'interrupt', definition: 'To stop the continuous progress of an activity or process.', example: 'Please do not interrupt while I am speaking.' },
    { id: '2-98', word: 'invisible', definition: 'Unable to be seen.', example: 'Air is invisible, but we can feel it when the wind blows.' },
    { id: '2-99', word: 'island', definition: 'A piece of land surrounded by water.', example: 'Hawaii is a beautiful island in the Pacific Ocean.' },
    { id: '2-100', word: 'journey', definition: 'An act of traveling from one place to another.', example: 'The long journey took them across many different countries.' },
  ]
};

export const WORD_BANK_3: WordBank = {
  id: 'bank-3',
  name: 'Age 9',
  words: [
    { id: '3-1', word: 'accurate', definition: 'Correct in all details; exact.', example: 'The weather forecast was accurate.' },
    { id: '3-2', word: 'address', definition: 'The particulars of the place where someone lives.', example: 'Write your address on the envelope.' },
    { id: '3-3', word: 'afford', definition: 'Have enough money to pay for.', example: 'I can\'t afford that expensive toy.' },
    { id: '3-4', word: 'alert', definition: 'Quick to notice any unusual and potentially dangerous circumstances.', example: 'The guard was alert during his shift.' },
    { id: '3-5', word: 'analyze', definition: 'Examine methodically and in detail.', example: 'We need to analyze the results of the experiment.' },
    { id: '3-6', word: 'ancestor', definition: 'A person from whom one is descended.', example: 'My ancestors came from Italy.' },
    { id: '3-7', word: 'annual', definition: 'Occurring once every year.', example: 'The school holds an annual talent show.' },
    { id: '3-8', word: 'apparent', definition: 'Clearly visible or understood; obvious.', example: 'It was apparent that he was lying.' },
    { id: '3-9', word: 'appropriate', definition: 'Suitable or proper in the circumstances.', example: 'Please wear appropriate clothes for the wedding.' },
    { id: '3-10', word: 'arena', definition: 'A level area surrounded by seats for spectators.', example: 'The basketball game was held in a large arena.' },
    { id: '3-11', word: 'arrest', definition: 'Seize (someone) by legal authority.', example: 'The police had to arrest the thief.' },
    { id: '3-12', word: 'ascend', definition: 'Go up or climb.', example: 'The hikers began to ascend the mountain.' },
    { id: '3-13', word: 'assist', definition: 'Help (someone), typically by doing a share of the work.', example: 'Can you assist me with these heavy bags?' },
    { id: '3-14', word: 'attempt', definition: 'Make an effort to achieve or complete something.', example: 'She will attempt to break the world record.' },
    { id: '3-15', word: 'attentive', definition: 'Paying close attention to something.', example: 'The students were very attentive during the lesson.' },
    { id: '3-16', word: 'awkward', definition: 'Causing or feeling embarrassment or inconvenience.', example: 'There was an awkward silence in the room.' },
    { id: '3-17', word: 'baggage', definition: 'Personal belongings packed in suitcases for traveling.', example: 'We checked our baggage at the airport.' },
    { id: '3-18', word: 'basic', definition: 'Forming an essential foundation or starting point.', example: 'Learning the alphabet is a basic skill.' },
    { id: '3-19', word: 'beacon', definition: 'A fire or light set up in a high position as a warning or signal.', example: 'The lighthouse is a beacon for ships.' },
    { id: '3-20', word: 'benefit', definition: 'An advantage or profit gained from something.', example: 'Exercise has many benefits for your health.' },
    { id: '3-21', word: 'betray', definition: 'Expose (one\'s country, a group, or a person) to danger by treacherously giving information to an enemy.', example: 'He would never betray his best friend.' },
    { id: '3-22', word: 'beverage', definition: 'A drink, especially one other than water.', example: 'Orange juice is a popular breakfast beverage.' },
    { id: '3-23', word: 'bland', definition: 'Lacking strong features or characteristics and therefore uninteresting.', example: 'The soup was a bit bland and needed salt.' },
    { id: '3-24', word: 'blossom', definition: 'A flower or a mass of flowers on a tree or bush.', example: 'The cherry trees are in full blossom.' },
    { id: '3-25', word: 'blunder', definition: 'A stupid or careless mistake.', example: 'Making that blunder cost the team the game.' },
    { id: '3-26', word: 'boast', definition: 'Talk with excessive pride and self-satisfaction about one\'s achievements.', example: 'He likes to boast about his high grades.' },
    { id: '3-27', word: 'border', definition: 'A line separating two countries or other areas.', example: 'We crossed the border into Canada.' },
    { id: '3-28', word: 'boundary', definition: 'A line that marks the limits of an area.', example: 'The river forms a natural boundary between the fields.' },
    { id: '3-29', word: 'brilliant', definition: 'Exceptionally clever or talented.', example: 'She is a brilliant scientist.' },
    { id: '3-30', word: 'brittle', definition: 'Hard but liable to break or shatter easily.', example: 'The old paper was dry and brittle.' },
    { id: '3-31', word: 'burden', definition: 'A load, especially a heavy one.', example: 'The heavy backpack was a burden to carry.' },
    { id: '3-32', word: 'campaign', definition: 'A series of military operations intended to achieve a particular objective.', example: 'The mayor started a campaign to clean up the park.' },
    { id: '3-33', word: 'capacity', definition: 'The maximum amount that something can contain.', example: 'The stadium has a large seating capacity.' },
    { id: '3-34', word: 'capital', definition: 'The most important city or town of a country or region.', example: 'Paris is the capital of France.' },
    { id: '3-35', word: 'carefree', definition: 'Free from anxiety or responsibility.', example: 'They had a carefree summer at the beach.' },
    { id: '3-36', word: 'cautious', definition: 'Careful to avoid potential problems or dangers.', example: 'Be cautious when walking on the icy sidewalk.' },
    { id: '3-37', word: 'celebrate', definition: 'Acknowledge (a significant or happy day or event) with a social gathering or enjoyable activity.', example: 'We will celebrate your birthday tonight.' },
    { id: '3-38', word: 'champion', definition: 'A person who has defeated all rivals in a competition.', example: 'He is the world chess champion.' },
    { id: '3-39', word: 'charity', definition: 'An organization set up to provide help and raise money for those in need.', example: 'She donated her old clothes to a local charity.' },
    { id: '3-40', word: 'cherish', definition: 'Protect and care for (someone) lovingly.', example: 'I will cherish this gift forever.' },
    { id: '3-41', word: 'circular', definition: 'Having the form of a circle.', example: 'The table has a circular top.' },
    { id: '3-42', word: 'clarify', definition: 'Make (a statement or situation) less confused and more clearly comprehensible.', example: 'Could you clarify what you meant by that?' },
    { id: '3-43', word: 'climate', definition: 'The weather conditions prevailing in an area in general or over a long period.', example: 'The desert has a very dry climate.' },
    { id: '3-44', word: 'collapse', definition: '(of a structure) fall down or in; give way.', example: 'The old bridge might collapse if it\'s not repaired.' },
    { id: '3-45', word: 'colleague', definition: 'A person with whom one works in a profession or business.', example: 'I\'m going to lunch with a colleague from work.' },
    { id: '3-46', word: 'collision', definition: 'An instance of one moving object or person striking violently against another.', example: 'The car was damaged in a collision.' },
    { id: '3-47', word: 'column', definition: 'A vertical pillar, typically cylindrical and made of stone or brick.', example: 'The building is supported by tall columns.' },
    { id: '3-48', word: 'combine', definition: 'Join or merge to form a single unit or substance.', example: 'You need to combine the flour and sugar.' },
    { id: '3-49', word: 'comfort', definition: 'A state of physical ease and freedom from pain or constraint.', example: 'The soft bed provided great comfort.' },
    { id: '3-50', word: 'command', definition: 'Give an authoritative order.', example: 'The general gave the command to attack.' },
    { id: '3-51', word: 'commerce', definition: 'The activity of buying and selling, especially on a large scale.', example: 'The city is a major center of commerce.' },
    { id: '3-52', word: 'companion', definition: 'A person or animal with whom one spends a lot of time.', example: 'The dog is a faithful companion.' },
    { id: '3-53', word: 'compassion', definition: 'Sympathetic pity and concern for the sufferings or misfortunes of others.', example: 'She showed great compassion for the homeless.' },
    { id: '3-54', word: 'compensate', definition: 'Give (someone) something, typically money, in recognition of loss, suffering, or injury.', example: 'The company will compensate you for your travel expenses.' },
    { id: '3-55', word: 'compete', definition: 'Strive to gain or win something by defeating or establishing superiority over others.', example: 'Many athletes will compete in the race.' },
    { id: '3-56', word: 'complex', definition: 'Consisting of many different and connected parts.', example: 'The human brain is a very complex organ.' },
    { id: '3-57', word: 'compose', definition: 'Write or create (a work of art, especially music or poetry).', example: 'He likes to compose his own songs.' },
    { id: '3-58', word: 'compound', definition: 'A thing that is composed of two or more separate elements; a mixture.', example: 'Water is a chemical compound.' },
    { id: '3-59', word: 'conceal', definition: 'Keep from sight; hide.', example: 'She tried to conceal her disappointment.' },
    { id: '3-60', word: 'concentrate', definition: 'Focus one\'s attention or mental effort on a particular object or activity.', example: 'I need to concentrate on my homework.' },
    { id: '3-61', word: 'concept', definition: 'An abstract idea; a general notion.', example: 'The teacher explained the concept of gravity.' },
    { id: '3-62', word: 'conclude', definition: 'Bring (something) to an end.', example: 'The meeting will conclude at noon.' },
    { id: '3-63', word: 'concrete', definition: 'Existing in a material or physical form; not abstract.', example: 'We need concrete evidence to prove the theory.' },
    { id: '3-64', word: 'confirm', definition: 'Establish the truth or correctness of (something previously believed or suspected).', example: 'The test results confirm the diagnosis.' },
    { id: '3-65', word: 'conflict', definition: 'A serious disagreement or argument.', example: 'The two countries are in a state of conflict.' },
    { id: '3-66', word: 'congratulate', definition: 'Give (someone) one\'s good wishes when something special or pleasant has happened to them.', example: 'I want to congratulate you on your graduation.' },
    { id: '3-67', word: 'conserve', definition: 'Protect (something, especially an environmentally or culturally important place or thing) from harm or destruction.', example: 'We must conserve our natural resources.' },
    { id: '3-68', word: 'consist', definition: 'Be composed or made up of.', example: 'The team will consist of ten players.' },
    { id: '3-69', word: 'constant', definition: 'Occurring continuously over a period of time.', example: 'The baby\'s constant crying kept everyone awake.' },
    { id: '3-70', word: 'construct', definition: 'Build or erect (something, typically a building, road, or machine).', example: 'They are going to construct a new school.' },
    { id: '3-71', word: 'consume', definition: 'Eat, drink, or ingest (food or drink).', example: 'Most people consume too much sugar.' },
    { id: '3-72', word: 'content', definition: 'In a state of peaceful happiness.', example: 'He was content to stay at home and read.' },
    { id: '3-73', word: 'contribute', definition: 'Give (something, especially money) in order to help achieve or provide something.', example: 'Many people contribute to the charity.' },
    { id: '3-74', word: 'control', definition: 'The power to influence or direct people\'s behavior or the course of events.', example: 'The pilot lost control of the plane.' },
    { id: '3-75', word: 'convenient', definition: 'Fitting in well with a person\'s needs, activities, and plans.', example: 'The new store is in a very convenient location.' },
    { id: '3-76', word: 'convert', definition: 'Change the form, character, or function of something.', example: 'They decided to convert the old barn into a house.' },
    { id: '3-77', word: 'convince', definition: 'Cause (someone) to believe firmly in the truth of something.', example: 'I tried to convince him to change his mind.' },
    { id: '3-78', word: 'cooperate', definition: 'Work jointly toward the same end.', example: 'The two teams decided to cooperate on the project.' },
    { id: '3-79', word: 'coordinate', definition: 'Bring the different elements of (a complex activity or organization) into a relationship that will ensure efficiency or harmony.', example: 'We need to coordinate our efforts.' },
    { id: '3-80', word: 'core', definition: 'The tough central part of various fruits, containing the seeds.', example: 'Don\'t eat the apple core.' },
    { id: '3-81', word: 'corporate', definition: 'Relating to a large company or group.', example: 'He works in the corporate office.' },
    { id: '3-82', word: 'correspond', definition: 'Have a close similarity; match or agree almost exactly.', example: 'The two stories correspond in every detail.' },
    { id: '3-83', word: 'corridor', definition: 'A long passage in a building from which doors lead into rooms.', example: 'The classroom is at the end of the corridor.' },
    { id: '3-84', word: 'costume', definition: 'A set of clothes in a style typical of a particular country or historical period.', example: 'She wore a pirate costume to the party.' },
    { id: '3-85', word: 'cottage', definition: 'A small simple house, typically one near the sea or in the country.', example: 'They stayed in a cozy cottage by the lake.' },
    { id: '3-86', word: 'council', definition: 'An advisory, deliberative, or legislative body of people formally constituted and meeting regularly.', example: 'The city council met to discuss the new budget.' },
    { id: '3-87', word: 'counsel', definition: 'Advice, especially that given formally.', example: 'He sought counsel from his lawyer.' },
    { id: '3-88', word: 'counter', definition: 'A long flat-topped fixture in a shop, bank, or restaurant across which business is conducted.', example: 'I left my keys on the kitchen counter.' },
    { id: '3-89', word: 'courage', definition: 'The ability to do something that frightens one.', example: 'It takes courage to stand up for what is right.' },
    { id: '3-90', word: 'course', definition: 'The route or direction followed by a ship, aircraft, road, or river.', example: 'The river changed its course after the flood.' },
    { id: '3-91', word: 'court', definition: 'A tribunal presided over by a judge, judges, or a magistrate in civil and criminal cases.', example: 'The case will be heard in court next week.' },
    { id: '3-92', word: 'cousin', definition: 'A child of one\'s uncle or aunt.', example: 'My cousin is coming to visit this weekend.' },
    { id: '3-93', word: 'craft', definition: 'An activity involving skill in making things by hand.', example: 'She enjoys various types of craft, like knitting.' },
    { id: '3-94', word: 'create', definition: 'Bring (something) into existence.', example: 'The artist wanted to create something beautiful.' },
    { id: '3-95', word: 'creature', definition: 'An animal, as distinct from a human being.', example: 'The forest is full of strange creatures.' },
    { id: '3-96', word: 'credit', definition: 'The ability of a customer to obtain goods or services before payment, based on the trust that payment will be made in the future.', example: 'The store gave him credit to buy the furniture.' },
    { id: '3-97', word: 'crisis', definition: 'A time of intense difficulty, trouble, or danger.', example: 'The country is facing an economic crisis.' },
    { id: '3-98', word: 'critic', definition: 'A person who expresses an unfavorable opinion of something.', example: 'The movie critic gave the film a bad review.' },
    { id: '3-99', word: 'critical', definition: 'Expressing adverse or disapproving comments or judgments.', example: 'He was very critical of the new policy.' },
    { id: '3-100', word: 'culture', definition: 'The arts and other manifestations of human intellectual achievement regarded collectively.', example: 'We should learn about different cultures.' },
  ]
};

export const WORD_BANK_4: WordBank = {
  id: 'bank-4',
  name: 'Age 11',
  words: [
    { id: '4-1', word: 'abundant', definition: 'Existing or available in large quantities; plentiful.', example: 'The garden was full of abundant flowers.' },
    { id: '4-2', word: 'accommodate', definition: '(of a physical space) provide lodging or sufficient space for.', example: 'The hotel can accommodate up to 200 guests.' },
    { id: '4-3', word: 'accumulate', definition: 'Gather together or acquire an increasing number or quantity of.', example: 'Dust began to accumulate on the old books.' },
    { id: '4-4', word: 'adapt', definition: 'Make (something) suitable for a new use or purpose; modify.', example: 'Animals have to adapt to their environment.' },
    { id: '4-5', word: 'adhere', definition: 'Stick fast to (a surface or substance).', example: 'The glue will help the pieces adhere to each other.' },
    { id: '4-6', word: 'agony', definition: 'Extreme physical or mental suffering.', example: 'He was in agony after breaking his leg.' },
    { id: '4-7', word: 'allegiance', definition: 'Loyalty or commitment of a subordinate to a superior or of an individual to a group or cause.', example: 'The soldiers swore allegiance to their country.' },
    { id: '4-8', word: 'ambition', definition: 'A strong desire to do or to achieve something, typically requiring determination and hard work.', example: 'Her ambition is to become a doctor.' },
    { id: '4-9', word: 'ample', definition: 'Enough or more than enough; plentiful.', example: 'There is ample parking space behind the building.' },
    { id: '4-10', word: 'anguish', definition: 'Severe mental or physical pain or suffering.', example: 'She felt great anguish after losing her pet.' },
    { id: '4-11', word: 'anticipate', definition: 'Regard as probable; expect or predict.', example: 'We anticipate a large crowd at the event.' },
    { id: '4-12', word: 'anxious', definition: 'Experiencing worry, unease, or nervousness.', example: 'He was anxious about the upcoming test.' },
    { id: '4-13', word: 'apparel', definition: 'Clothing.', example: 'The store sells a wide variety of sports apparel.' },
    { id: '4-14', word: 'appeal', definition: 'Make a serious or urgent request, typically to the public.', example: 'The police made an appeal for witnesses.' },
    { id: '4-15', word: 'apprehensive', definition: 'Anxious or fearful that something bad or unpleasant will happen.', example: 'She felt apprehensive about walking home alone.' },
    { id: '4-16', word: 'arid', definition: '(of land or a climate) having little or no rain; too dry or barren to support vegetation.', example: 'The desert is an arid region.' },
    { id: '4-17', word: 'arrogant', definition: 'Having or revealing an exaggerated sense of one\'s own importance or abilities.', example: 'He was so arrogant that he wouldn\'t listen to anyone else.' },
    { id: '4-18', word: 'awe', definition: 'A feeling of reverential respect mixed with fear or wonder.', example: 'We stood in awe of the massive mountain.' },
    { id: '4-19', word: 'barren', definition: '(of land) too poor to produce much or any vegetation.', example: 'The barren landscape was empty of life.' },
    { id: '4-20', word: 'beacon', definition: 'A fire or light set up in a high or prominent position as a warning, signal, or celebration.', example: 'The lighthouse served as a beacon for ships.' },
    { id: '4-21', word: 'beneficial', definition: 'Favorable or advantageous; resulting in good.', example: 'Regular exercise is beneficial for your health.' },
    { id: '4-22', word: 'blunder', definition: 'A stupid or careless mistake.', example: 'Making that blunder cost them the game.' },
    { id: '4-23', word: 'boisterous', definition: '(of a person, event, or behavior) noisy, energetic, and cheerful; rowdy.', example: 'The boisterous crowd cheered for their team.' },
    { id: '4-24', word: 'boycott', definition: 'Withdraw from commercial or social relations with (a country, organization, or person) as a punishment or protest.', example: 'The students decided to boycott the cafeteria.' },
    { id: '4-25', word: 'brevity', definition: 'Concise and exact use of words in writing or speech.', example: 'The brevity of the report was appreciated.' },
    { id: '4-26', word: 'brilliant', definition: 'Exceptionally clever or talented.', example: 'She is a brilliant student.' },
    { id: '4-27', word: 'browse', definition: 'Survey goods or text in a leisurely way.', example: 'I like to browse through the books at the library.' },
    { id: '4-28', word: 'bystander', definition: 'A person who is present at an event or incident but does not take part.', example: 'Several bystanders witnessed the accident.' },
    { id: '4-29', word: 'calamity', definition: 'An event causing great and often sudden damage or distress; a disaster.', example: 'The earthquake was a major calamity for the city.' },
    { id: '4-30', word: 'campaign', definition: 'A series of military operations intended to achieve a particular objective.', example: 'The politician started a campaign for re-election.' },
    { id: '4-31', word: 'capacity', definition: 'The maximum amount that something can contain.', example: 'The stadium has a seating capacity of 50,000.' },
    { id: '4-32', word: 'captive', definition: 'A person who has been taken prisoner or an animal that has been confined.', example: 'The soldiers were held captive for many months.' },
    { id: '4-33', word: 'carefree', definition: 'Free from anxiety or responsibility.', example: 'They had a carefree holiday in the mountains.' },
    { id: '4-34', word: 'cascade', definition: 'A small waterfall, typically one of several that fall in stages down a steep rocky slope.', example: 'The water began to cascade down the rocks.' },
    { id: '4-35', word: 'cause', definition: 'A person or thing that gives rise to an action, phenomenon, or condition.', example: 'The heavy rain was the cause of the flood.' },
    { id: '4-36', word: 'celebrate', definition: 'Acknowledge (a significant or happy day or event) with a social gathering or enjoyable activity.', example: 'We will celebrate the new year with fireworks.' },
    { id: '4-37', word: 'chamber', definition: 'A large room used for formal or public events.', example: 'The council met in the town hall chamber.' },
    { id: '4-38', word: 'charity', definition: 'An organization set up to provide help and raise money for those in need.', example: 'He donated money to a local charity.' },
    { id: '4-39', word: 'cherish', definition: 'Protect and care for (someone) lovingly.', example: 'I will cherish the memories of our trip.' },
    { id: '4-40', word: 'chronological', definition: '(of a record of events) starting with the earliest and following the order in which they occurred.', example: 'The events are listed in chronological order.' },
    { id: '4-41', word: 'clarity', definition: 'The quality of being coherent and intelligible.', example: 'The teacher explained the concept with great clarity.' },
    { id: '4-42', word: 'collaborate', definition: 'Work jointly on an activity, especially to produce or create something.', example: 'The two scientists decided to collaborate on the research.' },
    { id: '4-43', word: 'collide', definition: 'Hit with force when moving.', example: 'The two cars began to collide at the intersection.' },
    { id: '4-44', word: 'commend', definition: 'Praise formally or officially.', example: 'The principal decided to commend the students for their hard work.' },
    { id: '4-45', word: 'compact', definition: 'Closely and neatly packed together; dense.', example: 'The new camera is very small and compact.' },
    { id: '4-46', word: 'compatible', definition: '(of two things) able to exist or occur together without conflict.', example: 'The new software is compatible with your computer.' },
    { id: '4-47', word: 'compel', definition: 'Force or oblige (someone) to do something.', example: 'The law can compel you to testify in court.' },
    { id: '4-48', word: 'competent', definition: 'Having the necessary ability, knowledge, or skill to do something successfully.', example: 'She is a very competent and reliable employee.' },
    { id: '4-49', word: 'compile', definition: 'Produce (a list, report, or book) by assembling information collected from other sources.', example: 'We need to compile a list of all the guests.' },
    { id: '4-50', word: 'complement', definition: 'A thing that completes or brings to perfection.', example: 'The red scarf is a perfect complement to her outfit.' },
    { id: '4-51', word: 'compose', definition: 'Write or create (a work of art, especially music or poetry).', example: 'He spent months trying to compose his first symphony.' },
    { id: '4-52', word: 'compromise', definition: 'An agreement or a settlement of a dispute that is reached by each side making concessions.', example: 'The two sides finally reached a compromise.' },
    { id: '4-53', word: 'conceal', definition: 'Keep from sight; hide.', example: 'He tried to conceal his true feelings.' },
    { id: '4-54', word: 'concise', definition: 'Giving a lot of information clearly and in a few words; brief but comprehensive.', example: 'The instructions were clear and concise.' },
    { id: '4-55', word: 'conclude', definition: 'Bring (something) to an end.', example: 'The concert will conclude with a grand finale.' },
    { id: '4-56', word: 'concrete', definition: 'Existing in a material or physical form; not abstract.', example: 'The police have concrete evidence against the suspect.' },
    { id: '4-57', word: 'concur', definition: 'Be of the same opinion; agree.', example: 'I concur with your assessment of the situation.' },
    { id: '4-58', word: 'condense', definition: 'Make (something) denser or more concentrated.', example: 'You can condense the milk by boiling it.' },
    { id: '4-59', word: 'confine', definition: 'Keep or restrict someone or something within certain limits of (space, scope, quantity, or time).', example: 'Please confine your comments to the topic at hand.' },
    { id: '4-60', word: 'confirm', definition: 'Establish the truth or correctness of (something previously believed or suspected).', example: 'The witness was able to confirm the suspect\'s identity.' },
    { id: '4-61', word: 'conflict', definition: 'A serious disagreement or argument, typically a protracted one.', example: 'The two neighbors had a long-standing conflict over the fence.' },
    { id: '4-62', word: 'conform', definition: 'Comply with rules, standards, or laws.', example: 'All students must conform to the school\'s dress code.' },
    { id: '4-63', word: 'confront', definition: 'Face up to and deal with (a problem or difficult situation).', example: 'We must confront the challenges ahead.' },
    { id: '4-64', word: 'confuse', definition: 'Cause (someone) to become bewildered or perplexed.', example: 'The complex instructions might confuse the users.' },
    { id: '4-65', word: 'congratulate', definition: 'Give (someone) one\'s good wishes when something special or pleasant has happened to them.', example: 'I want to congratulate you on your promotion.' },
    { id: '4-66', word: 'congregate', definition: 'Gather into a crowd or mass.', example: 'The birds began to congregate on the power lines.' },
    { id: '4-67', word: 'connect', definition: 'Bring together or into contact so that a real or notional link is established.', example: 'The bridge will connect the two islands.' },
    { id: '4-68', word: 'conquer', definition: 'Overcome and take control of (a place or people) by use of military force.', example: 'The army managed to conquer the enemy\'s territory.' },
    { id: '4-69', word: 'conscience', definition: 'An inner feeling or voice viewed as acting as a guide to the rightness or wrongness of one\'s behavior.', example: 'He had a guilty conscience about lying.' },
    { id: '4-70', word: 'conscious', definition: 'Aware of and responding to one\'s surroundings; awake.', example: 'The patient was conscious and able to speak.' },
    { id: '4-71', word: 'consecutive', definition: 'Following each other continuously.', example: 'It rained for three consecutive days.' },
    { id: '4-72', word: 'consent', definition: 'Permission for something to happen or agreement to do something.', example: 'You need your parents\' consent to go on the trip.' },
    { id: '4-73', word: 'consequence', definition: 'A result or effect of an action or condition.', example: 'The accident was a consequence of his carelessness.' },
    { id: '4-74', word: 'conserve', definition: 'Protect (something, especially an environmentally or culturally important place or thing) from harm or destruction.', example: 'We should all try to conserve energy.' },
    { id: '4-75', word: 'consider', definition: 'Think carefully about (something), typically before making a decision.', example: 'Please consider all the options before you decide.' },
    { id: '4-76', word: 'consist', definition: 'Be composed or made up of.', example: 'The cake will consist of flour, sugar, and eggs.' },
    { id: '4-77', word: 'conspicuous', definition: 'Standing out so as to be clearly visible.', example: 'The bright yellow sign was very conspicuous.' },
    { id: '4-78', word: 'constant', definition: 'Occurring continuously over a period of time.', example: 'The constant noise from the street was very annoying.' },
    { id: '4-79', word: 'construct', definition: 'Build or erect (something, typically a building, road, or machine).', example: 'The engineers will construct a new bridge.' },
    { id: '4-80', word: 'consult', definition: 'Seek information or advice from (someone with expertise in a particular area).', example: 'You should consult a doctor if you feel unwell.' },
    { id: '4-81', word: 'consume', definition: 'Eat, drink, or ingest (food or drink).', example: 'The fire began to consume the entire building.' },
    { id: '4-82', word: 'contact', definition: 'The state or condition of physical touching.', example: 'Please keep in contact with us while you are away.' },
    { id: '4-83', word: 'contain', definition: 'Have or hold (someone or something) within.', example: 'The box will contain all your old toys.' },
    { id: '4-84', word: 'contemporary', definition: 'Living or occurring at the same time.', example: 'The museum features contemporary art from around the world.' },
    { id: '4-85', word: 'content', definition: 'In a state of peaceful happiness.', example: 'She was content with her simple life.' },
    { id: '4-86', word: 'contest', definition: 'An event in which people compete for supremacy in a particular activity or area.', example: 'He entered a singing contest at the local fair.' },
    { id: '4-87', word: 'context', definition: 'The circumstances that form the setting for an event, statement, or idea, and in terms of which it can be fully understood and assessed.', example: 'You need to consider the context of the quote.' },
    { id: '4-88', word: 'continent', definition: 'Any of the world\'s main continuous expanses of land.', example: 'Asia is the largest continent in the world.' },
    { id: '4-89', word: 'continue', definition: 'Persist in an activity or process.', example: 'The rain will continue throughout the day.' },
    { id: '4-90', word: 'contrast', definition: 'The state of being strikingly different from something else in juxtaposition or close association.', example: 'There is a sharp contrast between the two paintings.' },
    { id: '4-91', word: 'contribute', definition: 'Give (something, especially money) in order to help achieve or provide something.', example: 'Every small donation can contribute to the cause.' },
    { id: '4-92', word: 'control', definition: 'The power to influence or direct people\'s behavior or the course of events.', example: 'The driver lost control of the car on the icy road.' },
    { id: '4-93', word: 'controversy', definition: 'Disagreement, typically when prolonged, public, and heated.', example: 'The new law caused a lot of controversy.' },
    { id: '4-94', word: 'convenient', definition: 'Fitting in well with a person\'s needs, activities, and plans.', example: 'The new supermarket is in a very convenient location.' },
    { id: '4-95', word: 'conversation', definition: 'A talk, especially an informal one, between two or more people, in which news and ideas are exchanged.', example: 'We had a long conversation about our future plans.' },
    { id: '4-96', word: 'convert', definition: 'Change the form, character, or function of something.', example: 'They decided to convert the old factory into apartments.' },
    { id: '4-97', word: 'convince', definition: 'Cause (someone) to believe firmly in the truth of something.', example: 'I managed to convince him that I was right.' },
    { id: '4-98', word: 'cooperate', definition: 'Work jointly toward the same end.', example: 'The two countries agreed to cooperate on environmental issues.' },
    { id: '4-99', word: 'coordinate', definition: 'Bring the different elements of (a complex activity or organization) into a relationship that will ensure efficiency or harmony.', example: 'We need to coordinate our schedules for the meeting.' },
    { id: '4-100', word: 'cope', definition: '(of a person) deal effectively with something difficult.', example: 'It can be hard to cope with the loss of a loved one.' },
  ]
};

export const WORD_BANK_5: WordBank = {
  id: 'bank-5',
  name: 'Age 10',
  words: [
    { id: '5-1', word: 'abundant', definition: 'Existing or available in large quantities; plentiful.', example: 'The garden was full of abundant flowers.' },
    { id: '5-2', word: 'accommodate', definition: '(of a physical space) provide lodging or sufficient space for.', example: 'The hotel can accommodate up to 200 guests.' },
    { id: '5-3', word: 'accumulate', definition: 'Gather together or acquire an increasing number or quantity of.', example: 'Dust began to accumulate on the old books.' },
    { id: '5-4', word: 'adapt', definition: 'Make (something) suitable for a new use or purpose; modify.', example: 'Animals have to adapt to their environment.' },
    { id: '5-5', word: 'adhere', definition: 'Stick fast to (a surface or substance).', example: 'The glue will help the pieces adhere to each other.' },
    { id: '5-6', word: 'agony', definition: 'Extreme physical or mental suffering.', example: 'He was in agony after breaking his leg.' },
    { id: '5-7', word: 'allegiance', definition: 'Loyalty or commitment of a subordinate to a superior or of an individual to a group or cause.', example: 'The soldiers swore allegiance to their country.' },
    { id: '5-8', word: 'ambition', definition: 'A strong desire to do or to achieve something, typically requiring determination and hard work.', example: 'Her ambition is to become a doctor.' },
    { id: '5-9', word: 'ample', definition: 'Enough or more than enough; plentiful.', example: 'There is ample parking space behind the building.' },
    { id: '5-10', word: 'anguish', definition: 'Severe mental or physical pain or suffering.', example: 'She felt great anguish after losing her pet.' },
    { id: '5-11', word: 'anticipate', definition: 'Regard as probable; expect or predict.', example: 'We anticipate a large crowd at the event.' },
    { id: '5-12', word: 'anxious', definition: 'Experiencing worry, unease, or nervousness.', example: 'He was anxious about the upcoming test.' },
    { id: '5-13', word: 'apparel', definition: 'Clothing.', example: 'The store sells a wide variety of sports apparel.' },
    { id: '5-14', word: 'appeal', definition: 'Make a serious or urgent request, typically to the public.', example: 'The police made an appeal for witnesses.' },
    { id: '5-15', word: 'apprehensive', definition: 'Anxious or fearful that something bad or unpleasant will happen.', example: 'She felt apprehensive about walking home alone.' },
    { id: '5-16', word: 'arid', definition: '(of land or a climate) having little or no rain; too dry or barren to support vegetation.', example: 'The desert is an arid region.' },
    { id: '5-17', word: 'arrogant', definition: 'Having or revealing an exaggerated sense of one\'s own importance or abilities.', example: 'He was so arrogant that he wouldn\'t listen to anyone else.' },
    { id: '5-18', word: 'awe', definition: 'A feeling of reverential respect mixed with fear or wonder.', example: 'We stood in awe of the massive mountain.' },
    { id: '5-19', word: 'barren', definition: '(of land) too poor to produce much or any vegetation.', example: 'The barren landscape was empty of life.' },
    { id: '5-20', word: 'beacon', definition: 'A fire or light set up in a high or prominent position as a warning, signal, or celebration.', example: 'The lighthouse served as a beacon for ships.' },
    { id: '5-21', word: 'beneficial', definition: 'Favorable or advantageous; resulting in good.', example: 'Regular exercise is beneficial for your health.' },
    { id: '5-22', word: 'blunder', definition: 'A stupid or careless mistake.', example: 'Making that blunder cost them the game.' },
    { id: '5-23', word: 'boisterous', definition: '(of a person, event, or behavior) noisy, energetic, and cheerful; rowdy.', example: 'The boisterous crowd cheered for their team.' },
    { id: '5-24', word: 'boycott', definition: 'Withdraw from commercial or social relations with (a country, organization, or person) as a punishment or protest.', example: 'The students decided to boycott the cafeteria.' },
    { id: '5-25', word: 'brevity', definition: 'Concise and exact use of words in writing or speech.', example: 'The brevity of the report was appreciated.' },
    { id: '5-26', word: 'brilliant', definition: 'Exceptionally clever or talented.', example: 'She is a brilliant student.' },
    { id: '5-27', word: 'browse', definition: 'Survey goods or text in a leisurely way.', example: 'I like to browse through the books at the library.' },
    { id: '5-28', word: 'bystander', definition: 'A person who is present at an event or incident but does not take part.', example: 'Several bystanders witnessed the accident.' },
    { id: '5-29', word: 'calamity', definition: 'An event causing great and often sudden damage or distress; a disaster.', example: 'The earthquake was a major calamity for the city.' },
    { id: '5-30', word: 'campaign', definition: 'A series of military operations intended to achieve a particular objective.', example: 'The politician started a campaign for re-election.' },
    { id: '5-31', word: 'capacity', definition: 'The maximum amount that something can contain.', example: 'The stadium has a seating capacity of 50,000.' },
    { id: '5-32', word: 'captive', definition: 'A person who has been taken prisoner or an animal that has been confined.', example: 'The soldiers were held captive for many months.' },
    { id: '5-33', word: 'carefree', definition: 'Free from anxiety or responsibility.', example: 'They had a carefree holiday in the mountains.' },
    { id: '5-34', word: 'cascade', definition: 'A small waterfall, typically one of several that fall in stages down a steep rocky slope.', example: 'The water began to cascade down the rocks.' },
    { id: '5-35', word: 'cause', definition: 'A person or thing that gives rise to an action, phenomenon, or condition.', example: 'The heavy rain was the cause of the flood.' },
    { id: '5-36', word: 'celebrate', definition: 'Acknowledge (a significant or happy day or event) with a social gathering or enjoyable activity.', example: 'We will celebrate the new year with fireworks.' },
    { id: '5-37', word: 'chamber', definition: 'A large room used for formal or public events.', example: 'The council met in the town hall chamber.' },
    { id: '5-38', word: 'charity', definition: 'An organization set up to provide help and raise money for those in need.', example: 'He donated money to a local charity.' },
    { id: '5-39', word: 'cherish', definition: 'Protect and care for (someone) lovingly.', example: 'I will cherish the memories of our trip.' },
    { id: '5-40', word: 'chronological', definition: '(of a record of events) starting with the earliest and following the order in which they occurred.', example: 'The events are listed in chronological order.' },
    { id: '5-41', word: 'clarity', definition: 'The quality of being coherent and intelligible.', example: 'The teacher explained the concept with great clarity.' },
    { id: '5-42', word: 'collaborate', definition: 'Work jointly on an activity, especially to produce or create something.', example: 'The two scientists decided to collaborate on the research.' },
    { id: '5-43', word: 'collide', definition: 'Hit with force when moving.', example: 'The two cars began to collide at the intersection.' },
    { id: '5-44', word: 'commend', definition: 'Praise formally or officially.', example: 'The principal decided to commend the students for their hard work.' },
    { id: '5-45', word: 'compact', definition: 'Closely and neatly packed together; dense.', example: 'The new camera is very small and compact.' },
    { id: '5-46', word: 'compatible', definition: '(of two things) able to exist or occur together without conflict.', example: 'The new software is compatible with your computer.' },
    { id: '5-47', word: 'compel', definition: 'Force or oblige (someone) to do something.', example: 'The law can compel you to testify in court.' },
    { id: '5-48', word: 'competent', definition: 'Having the necessary ability, knowledge, or skill to do something successfully.', example: 'She is a very competent and reliable employee.' },
    { id: '5-49', word: 'compile', definition: 'Produce (a list, report, or book) by assembling information collected from other sources.', example: 'We need to compile a list of all the guests.' },
    { id: '5-50', word: 'complement', definition: 'A thing that completes or brings to perfection.', example: 'The red scarf is a perfect complement to her outfit.' },
    { id: '5-51', word: 'compose', definition: 'Write or create (a work of art, especially music or poetry).', example: 'He spent months trying to compose his first symphony.' },
    { id: '5-52', word: 'compromise', definition: 'An agreement or a settlement of a dispute that is reached by each side making concessions.', example: 'The two sides finally reached a compromise.' },
    { id: '5-53', word: 'conceal', definition: 'Keep from sight; hide.', example: 'He tried to conceal his true feelings.' },
    { id: '5-54', word: 'concise', definition: 'Giving a lot of information clearly and in a few words; brief but comprehensive.', example: 'The instructions were clear and concise.' },
    { id: '5-55', word: 'conclude', definition: 'Bring (something) to an end.', example: 'The concert will conclude with a grand finale.' },
    { id: '5-56', word: 'concrete', definition: 'Existing in a material or physical form; not abstract.', example: 'The police have concrete evidence against the suspect.' },
    { id: '5-57', word: 'concur', definition: 'Be of the same opinion; agree.', example: 'I concur with your assessment of the situation.' },
    { id: '5-58', word: 'condense', definition: 'Make (something) denser or more concentrated.', example: 'You can condense the milk by boiling it.' },
    { id: '5-59', word: 'confine', definition: 'Keep or restrict someone or something within certain limits of (space, scope, quantity, or time).', example: 'Please confine your comments to the topic at hand.' },
    { id: '5-60', word: 'confirm', definition: 'Establish the truth or correctness of (something previously believed or suspected).', example: 'The witness was able to confirm the suspect\'s identity.' },
    { id: '5-61', word: 'conflict', definition: 'A serious disagreement or argument, typically a protracted one.', example: 'The two neighbors had a long-standing conflict over the fence.' },
    { id: '5-62', word: 'conform', definition: 'Comply with rules, standards, or laws.', example: 'All students must conform to the school\'s dress code.' },
    { id: '5-63', word: 'confront', definition: 'Face up to and deal with (a problem or difficult situation).', example: 'We must confront the challenges ahead.' },
    { id: '5-64', word: 'confuse', definition: 'Cause (someone) to become bewildered or perplexed.', example: 'The complex instructions might confuse the users.' },
    { id: '5-65', word: 'congratulate', definition: 'Give (someone) one\'s good wishes when something special or pleasant has happened to them.', example: 'I want to congratulate you on your promotion.' },
    { id: '5-66', word: 'congregate', definition: 'Gather into a crowd or mass.', example: 'The birds began to congregate on the power lines.' },
    { id: '5-67', word: 'connect', definition: 'Bring together or into contact so that a real or notional link is established.', example: 'The bridge will connect the two islands.' },
    { id: '5-68', word: 'conquer', definition: 'Overcome and take control of (a place or people) by use of military force.', example: 'The army managed to conquer the enemy\'s territory.' },
    { id: '5-69', word: 'conscience', definition: 'An inner feeling or voice viewed as acting as a guide to the rightness or wrongness of one\'s behavior.', example: 'He had a guilty conscience about lying.' },
    { id: '5-70', word: 'conscious', definition: 'Aware of and responding to one\'s surroundings; awake.', example: 'The patient was conscious and able to speak.' },
    { id: '5-71', word: 'consecutive', definition: 'Following each other continuously.', example: 'It rained for three consecutive days.' },
    { id: '5-72', word: 'consent', definition: 'Permission for something to happen or agreement to do something.', example: 'You need your parents\' consent to go on the trip.' },
    { id: '5-73', word: 'consequence', definition: 'A result or effect of an action or condition.', example: 'The accident was a consequence of his carelessness.' },
    { id: '5-74', word: 'conserve', definition: 'Protect (something, especially an environmentally or culturally important place or thing) from harm or destruction.', example: 'We should all try to conserve energy.' },
    { id: '5-75', word: 'consider', definition: 'Think carefully about (something), typically before making a decision.', example: 'Please consider all the options before you decide.' },
    { id: '5-76', word: 'consist', definition: 'Be composed or made up of.', example: 'The cake will consist of flour, sugar, and eggs.' },
    { id: '5-77', word: 'conspicuous', definition: 'Standing out so as to be clearly visible.', example: 'The bright yellow sign was very conspicuous.' },
    { id: '5-78', word: 'constant', definition: 'Occurring continuously over a period of time.', example: 'The constant noise from the street was very annoying.' },
    { id: '5-79', word: 'construct', definition: 'Build or erect (something, typically a building, road, or machine).', example: 'The engineers will construct a new bridge.' },
    { id: '5-80', word: 'consult', definition: 'Seek information or advice from (someone with expertise in a particular area).', example: 'You should consult a doctor if you feel unwell.' },
    { id: '5-81', word: 'consume', definition: 'Eat, drink, or ingest (food or drink).', example: 'The fire began to consume the entire building.' },
    { id: '5-82', word: 'contact', definition: 'The state or condition of physical touching.', example: 'Please keep in contact with us while you are away.' },
    { id: '5-83', word: 'contain', definition: 'Have or hold (someone or something) within.', example: 'The box will contain all your old toys.' },
    { id: '5-84', word: 'contemporary', definition: 'Living or occurring at the same time.', example: 'The museum features contemporary art from around the world.' },
    { id: '5-85', word: 'content', definition: 'In a state of peaceful happiness.', example: 'She was content with her simple life.' },
    { id: '5-86', word: 'contest', definition: 'An event in which people compete for supremacy in a particular activity or area.', example: 'He entered a singing contest at the local fair.' },
    { id: '5-87', word: 'context', definition: 'The circumstances that form the setting for an event, statement, or idea, and in terms of which it can be fully understood and assessed.', example: 'You need to consider the context of the quote.' },
    { id: '5-88', word: 'continent', definition: 'Any of the world\'s main continuous expanses of land.', example: 'Asia is the largest continent in the world.' },
    { id: '5-89', word: 'continue', definition: 'Persist in an activity or process.', example: 'The rain will continue throughout the day.' },
    { id: '5-90', word: 'contrast', definition: 'The state of being strikingly different from something else in juxtaposition or close association.', example: 'There is a sharp contrast between the two paintings.' },
    { id: '5-91', word: 'contribute', definition: 'Give (something, especially money) in order to help achieve or provide something.', example: 'Every small donation can contribute to the cause.' },
    { id: '5-92', word: 'control', definition: 'The power to influence or direct people\'s behavior or the course of events.', example: 'The driver lost control of the car on the icy road.' },
    { id: '5-93', word: 'controversy', definition: 'Disagreement, typically when prolonged, public, and heated.', example: 'The new law caused a lot of controversy.' },
    { id: '5-94', word: 'convenient', definition: 'Fitting in well with a person\'s needs, activities, and plans.', example: 'The new supermarket is in a very convenient location.' },
    { id: '5-95', word: 'conversation', definition: 'A talk, especially an informal one, between two or more people, in which news and ideas are exchanged.', example: 'We had a long conversation about our future plans.' },
    { id: '5-96', word: 'convert', definition: 'Change the form, character, or function of something.', example: 'They decided to convert the old factory into apartments.' },
    { id: '5-97', word: 'convince', definition: 'Cause (someone) to believe firmly in the truth of something.', example: 'I managed to convince him that I was right.' },
    { id: '5-98', word: 'cooperate', definition: 'Work jointly toward the same end.', example: 'The two countries agreed to cooperate on environmental issues.' },
    { id: '5-99', word: 'coordinate', definition: 'Bring the different elements of (a complex activity or organization) into a relationship that will ensure efficiency or harmony.', example: 'We need to coordinate our schedules for the meeting.' },
    { id: '5-100', word: 'cope', definition: '(of a person) deal effectively with something difficult.', example: 'It can be hard to cope with the loss of a loved one.' },
  ]
};

export const ALL_WORD_BANKS = [WORD_BANK_2, WORD_BANK_3, WORD_BANK_5, WORD_BANK_4, WORD_BANK_1];
