import { Word, WordBank } from './types';

export const WORD_BANK_1: WordBank = {
  id: 'bank-1',
  name: '12 years word list 1',
  words: [
    { id: '1', word: 'abundant', definition: 'Existing or available in large quantities; plentiful.', example: 'The garden was full of abundant flowers in the spring.' },
    { id: '2', word: 'beacon', definition: 'A fire or light set up in a high or prominent position as a warning, signal, or celebration.', example: 'The lighthouse served as a beacon for ships at sea.' },
    { id: '3', word: 'clarity', definition: 'The quality of being coherent and intelligible.', example: 'The teacher explained the math problem with great clarity.' },
    { id: '4', word: 'deteriorate', definition: 'Become progressively worse.', example: 'The old house began to deteriorate after years of neglect.' },
    { id: '5', word: 'elude', definition: 'Evade or escape from (a danger, enemy, or pursuer), typically in a skillful or cunning way.', example: 'The clever fox managed to elude the hunters.' },
    { id: '6', word: 'factor', definition: 'A circumstance, fact, or influence that contributes to a result or outcome.', example: 'Hard work is a key factor in achieving success.' },
    { id: '7', word: 'garment', definition: 'An item of clothing.', example: 'She wore a beautiful silk garment to the party.' },
    { id: '8', word: 'hostile', definition: 'Unfriendly; antagonistic.', example: 'The two rival teams had a hostile relationship.' },
    { id: '9', word: 'improvise', definition: 'Create and perform (music, drama, or verse) spontaneously without preparation.', example: 'When he forgot his lines, he had to improvise.' },
    { id: '10', word: 'jovial', definition: 'Cheerful and friendly.', example: 'The party was full of jovial people celebrating.' },
    { id: '11', word: 'knack', definition: 'An acquired or natural skill at performing a task.', example: 'She has a knack for solving difficult puzzles.' },
    { id: '12', word: 'leeway', definition: 'The amount of freedom to move or act that is available.', example: 'The boss gave him some leeway to finish the project.' },
    { id: '13', word: 'marvel', definition: 'Be filled with wonder or astonishment.', example: 'We could only marvel at the beauty of the sunset.' },
    { id: '14', word: 'nurture', definition: 'Care for and encourage the growth or development of.', example: 'It is important to nurture young plants so they grow strong.' },
    { id: '15', word: 'obstacle', definition: 'A thing that blocks one\'s way or prevents or hinders progress.', example: 'The fallen tree was an obstacle on the road.' },
    { id: '16', word: 'plummet', definition: 'Fall or drop straight down at high speed.', example: 'The temperature began to plummet as the sun went down.' },
    { id: '17', word: 'quench', definition: 'Satisfy (one\'s thirst) by drinking.', example: 'A cold glass of water will quench your thirst.' },
    { id: '18', word: 'reluctant', definition: 'Unwilling and hesitant; disinclined.', example: 'He was reluctant to share his secret with anyone.' },
    { id: '19', word: 'salvage', definition: 'Rescue (a wrecked or disabled ship or its cargo) from loss at sea.', example: 'They managed to salvage some old photos from the fire.' },
    { id: '20', word: 'terrain', definition: 'A stretch of land, especially with regard to its physical features.', example: 'The rugged terrain made the hike very challenging.' },
    { id: '21', word: 'unanimous', definition: '(of two or more people) fully in agreement.', example: 'The class was unanimous in choosing the field trip destination.' },
    { id: '22', word: 'vacant', definition: '(of a premise) having no fixtures, furniture, or inhabitants; empty.', example: 'The old building has been vacant for many years.' },
    { id: '23', word: 'weary', definition: 'Feeling or showing tiredness, especially as a result of excessive exertion or lack of sleep.', example: 'The long journey made the travelers very weary.' },
    { id: '24', word: 'yield', definition: 'Produce or provide (a natural, agricultural, or industrial product).', example: 'The apple trees yield a lot of fruit every year.' },
    { id: '25', word: 'zeal', definition: 'Great energy or enthusiasm in pursuit of a cause or an objective.', example: 'She worked with great zeal to finish the project on time.' },
    { id: '26', word: 'anticipate', definition: 'Regard as probable; expect or predict.', example: 'We anticipate a large crowd at the school play.' },
    { id: '27', word: 'barren', definition: '(of land) too poor to produce much or any vegetation.', example: 'The desert is a barren landscape with very few plants.' },
    { id: '28', word: 'conspicuous', definition: 'Standing out so as to be clearly visible.', example: 'The bright red sign was very conspicuous.' },
    { id: '29', word: 'dense', definition: 'Closely compacted in substance.', example: 'The forest was so dense that it was hard to see through the trees.' },
    { id: '30', word: 'equivalent', definition: 'Equal in value, amount, function, meaning, etc.', example: 'One dollar is equivalent to four quarters.' },
    { id: '31', word: 'formulate', definition: 'Create or devise methodically (a strategy or a proposal).', example: 'The team met to formulate a plan for the project.' },
    { id: '32', word: 'genuine', definition: 'Truly what something is said to be; authentic.', example: 'She showed genuine concern for her friend\'s well-being.' },
    { id: '33', word: 'hazardous', definition: 'Risky; dangerous.', example: 'The icy roads made driving very hazardous.' },
    { id: '34', word: 'ignite', definition: 'Catch fire or cause to catch fire.', example: 'A small spark can ignite a large fire.' },
    { id: '35', word: 'jargon', definition: 'Special words or expressions that are used by a particular profession or group.', example: 'The computer programmer used a lot of technical jargon.' },
    { id: '36', word: 'kinship', definition: 'Blood relationship.', example: 'The two families shared a strong sense of kinship.' },
    { id: '37', word: 'linger', definition: 'Stay in a place longer than necessary because of a reluctance to leave.', example: 'The smell of fresh cookies seemed to linger in the air.' },
    { id: '38', word: 'meager', definition: '(of something provided or available) lacking in quantity or quality.', example: 'The travelers had only a meager supply of food.' },
    { id: '39', word: 'negotiate', definition: 'Try to reach an agreement or compromise by discussion with others.', example: 'They had to negotiate a fair price for the car.' },
    { id: '40', word: 'optimist', definition: 'A person who tends to be hopeful and confident about the future.', example: 'An optimist always looks on the bright side of life.' },
    { id: '41', word: 'peculiar', definition: 'Strange or odd; unusual.', example: 'The cat had a peculiar habit of sleeping in the sink.' },
    { id: '42', word: 'quest', definition: 'A long or arduous search for something.', example: 'The knights went on a quest to find the lost treasure.' },
    { id: '43', word: 'retrieve', definition: 'Get or bring (something) back from somewhere.', example: 'The dog ran to retrieve the ball.' },
    { id: '44', word: 'skeptical', definition: 'Not easily convinced; having doubts or reservations.', example: 'She was skeptical about the new plan at first.' },
    { id: '45', word: 'toxic', definition: 'Poisonous.', example: 'Some plants are toxic if they are eaten.' },
    { id: '46', word: 'unique', definition: 'Being the only one of its kind; unlike anything else.', example: 'Every snowflake is unique and different.' },
    { id: '47', word: 'vibrant', definition: 'Full of energy and enthusiasm.', example: 'The city has a vibrant culture with many festivals.' },
    { id: '48', word: 'wary', definition: 'Feeling or showing caution about possible dangers or problems.', example: 'Be wary of strangers who ask for your personal information.' },
    { id: '49', word: 'xenon', definition: 'A chemical element, a noble gas used in some specialized lamps.', example: 'Xenon is used in some types of high-intensity lamps.' },
    { id: '50', word: 'yearn', definition: 'Have an intense feeling of longing for something.', example: 'She began to yearn for the comfort of her own home.' },
    { id: '51', word: 'ambition', definition: 'A strong desire to do or to achieve something.', example: 'His ambition is to become a famous scientist.' },
    { id: '52', word: 'benevolent', definition: 'Well meaning and kindly.', example: 'The benevolent old man donated money to the charity.' },
    { id: '53', word: 'capacity', definition: 'The maximum amount that something can contain.', example: 'The stadium has a large capacity for spectators.' },
    { id: '54', word: 'drastic', definition: 'Likely to have a strong or far-reaching effect; radical and extreme.', example: 'The company had to take drastic measures to save money.' },
    { id: '55', word: 'efficient', definition: '(of a system or machine) achieving maximum productivity with minimum wasted effort or expense.', example: 'The new engine is much more efficient than the old one.' },
    { id: '56', word: 'frugal', definition: 'Sparing or economical with regard to money or food.', example: 'She is very frugal and always looks for the best deals.' },
    { id: '57', word: 'generate', definition: 'Cause (a, especially an emotion or situation) to arise or come about.', example: 'The new project will generate a lot of excitement.' },
    { id: '58', word: 'habitat', definition: 'The natural home or environment of an animal, plant, or other organism.', example: 'The forest is the natural habitat of many animals.' },
    { id: '59', word: 'inevitable', definition: 'Certain to happen; unavoidable.', example: 'It was inevitable that they would eventually meet again.' },
    { id: '60', word: 'jubilant', definition: 'Feeling or expressing great happiness and triumph.', example: 'The crowd was jubilant after the team won the game.' },
    { id: '61', word: 'latitude', definition: 'The angular distance of a place north or south of the earth\'s equator.', example: 'The ship\'s position was determined by its latitude and longitude.' },
    { id: '62', word: 'monotonous', definition: 'Dull, tedious, and repetitious; lacking in variety and interest.', example: 'The long drive was monotonous and boring.' },
    { id: '63', word: 'noteworthy', definition: 'Interesting, significant, or unusual.', example: 'The discovery of the new planet was a noteworthy event.' },
    { id: '64', word: 'objective', definition: '(of a person or their judgment) not influenced by personal feelings or opinions.', example: 'A judge must remain objective and fair.' },
    { id: '65', word: 'paraphrase', definition: 'Express the meaning of (the writer or speaker or something written or spoken) using different words.', example: 'Can you paraphrase the main idea of the story?' },
    { id: '66', word: 'quandary', definition: 'A state of perplexity or uncertainty over what to do in a difficult situation.', example: 'I am in a quandary about which path to take.' },
    { id: '67', word: 'rigorous', definition: 'Extremely thorough, exhaustive, or accurate.', example: 'The athletes went through a rigorous training program.' },
    { id: '68', word: 'substitute', definition: 'A person or thing acting or serving in place of another.', example: 'The teacher had a substitute for the day.' },
    { id: '69', word: 'tangible', definition: 'Perceptible by touch.', example: 'The tension in the room was almost tangible.' },
    { id: '70', word: 'ultimate', definition: 'Being or happening at the end of a process; final.', example: 'Winning the championship was their ultimate goal.' },
    { id: '71', word: 'validate', definition: 'Check or prove the validity or accuracy of (something).', example: 'The scientist needed to validate the results of the experiment.' },
    { id: '72', word: 'wholesome', definition: 'Conducive to or suggestive of good health and physical well-being.', example: 'The family enjoyed a wholesome meal together.' },
    { id: '73', word: 'yield', definition: 'To give up or surrender.', example: 'The army was forced to yield to the enemy.' },
    { id: '74', word: 'abbreviate', definition: 'Shorten (a word, phrase, or text).', example: 'We often abbreviate the word "doctor" as "Dr."' },
    { id: '75', word: 'boisterous', definition: '(of a person, event, or behavior) noisy, energetic, and cheerful; rowdy.', example: 'The boisterous children were playing loudly in the park.' },
    { id: '76', word: 'collaborate', definition: 'Work jointly on an activity, especially to produce or create something.', example: 'The two artists decided to collaborate on a new project.' },
    { id: '77', word: 'diligent', definition: 'Having or showing care and conscientiousness in one\'s work or duties.', example: 'A diligent student always finishes their homework on time.' },
    { id: '78', word: 'exaggerate', definition: 'Represent (something) as being better or worse than it really is.', example: 'Don\'t exaggerate the size of the fish you caught!' },
    { id: '79', word: 'futile', definition: 'Incapable of producing any useful result; pointless.', example: 'It is futile to argue with someone who won\'t listen.' },
    { id: '80', word: 'grievance', definition: 'A real or imagined wrong or other cause for complaint or protest.', example: 'The workers filed a grievance about their low pay.' },
    { id: '81', word: 'hypocrisy', definition: 'The practice of claiming to have moral standards or beliefs to which one\'s own behavior does not conform.', example: 'It is hypocrisy to tell others to be honest when you are not.' },
    { id: '82', word: 'impartial', definition: 'Treating all rivals or disputants equally; fair and just.', example: 'A good referee must be impartial and fair to both teams.' },
    { id: '83', word: 'jeopardize', definition: 'Put (someone or something) into a situation in which there is a danger of loss, harm, or failure.', example: 'Don\'t jeopardize your health by eating too much junk food.' },
    { id: '84', word: 'legislation', definition: 'Laws, considered collectively.', example: 'The government passed new legislation to protect the environment.' },
    { id: '85', word: 'meticulous', definition: 'Showing great attention to detail; very careful and precise.', example: 'She is meticulous about keeping her room clean and organized.' },
    { id: '86', word: 'nonchalant', definition: '(of a person or manner) feeling or appearing casually calm and relaxed.', example: 'He was nonchalant about winning the prize, as if it didn\'t matter.' },
    { id: '87', word: 'obscure', definition: 'Not discovered or known about; uncertain.', example: 'The meaning of the poem was obscure and difficult to understand.' },
    { id: '88', word: 'pessimist', definition: 'A person who tends to see the worst aspect of things or believe that the worst will happen.', example: 'A pessimist always expects things to go wrong.' },
    { id: '89', word: 'reiterate', definition: 'Say something again or a number of times, typically for emphasis or clarity.', example: 'Let me reiterate the importance of safety.' },
    { id: '90', word: 'strenuous', definition: 'Requiring or using great exertion.', example: 'The hike up the mountain was very strenuous.' },
    { id: '91', word: 'tentative', definition: 'Not certain or fixed; provisional.', example: 'We made a tentative plan for the weekend.' },
    { id: '92', word: 'unison', definition: 'Simultaneous performance of action or utterance of speech.', example: 'The choir sang the song in perfect unison.' },
    { id: '93', word: 'versatile', definition: 'Able to adapt or be turned to many functions or activities.', example: 'A Swiss Army knife is a very versatile tool.' },
    { id: '94', word: 'widespread', definition: 'Found or distributed over a large area or number of people.', example: 'The flu was widespread throughout the school.' },
    { id: '95', word: 'adversary', definition: 'One\'s opponent in a contest, conflict, or dispute.', example: 'He knew that his adversary was a strong player.' },
    { id: '96', word: 'bizarre', definition: 'Very strange or unusual, especially so as to cause interest or amusement.', example: 'The movie had a bizarre plot that was hard to follow.' },
    { id: '97', word: 'chronological', definition: '(of a record of events) starting with the earliest and following the order in which they occurred.', example: 'The history book was arranged in chronological order.' },
    { id: '98', word: 'discretion', definition: 'The quality of behaving or speaking in such a way as to avoid causing offense or revealing private information.', example: 'The doctor handled the sensitive information with great discretion.' },
    { id: '99', word: 'eloquent', definition: 'Fluent or persuasive in speaking or writing.', example: 'She gave an eloquent presentation that impressed everyone.' },
    { id: '100', word: 'formidable', definition: 'Inspiring fear or respect through being impressively large, powerful, intense, or capable.', example: 'The mountain range was a formidable challenge for the climbers.' },
    { id: '101', word: 'boron', definition: 'The chemical element of atomic number 5, a nonmetallic solid.', example: 'Boron is used in the production of heat-resistant glass.' },
  ]
};

export const WORDS_100 = WORD_BANK_1.words;
